
package com.claro.ppamdiag;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IMasociarWS", targetNamespace = "http://ppamdiag.claro.com/", wsdlLocation = "http://localhost:8080/PPAMDiag/IMasociarWS?WSDL")
public class IMasociarWS_Service
    extends Service
{

    private final static URL IMASOCIARWS_WSDL_LOCATION;
    private final static WebServiceException IMASOCIARWS_EXCEPTION;
    private final static QName IMASOCIARWS_QNAME = new QName("http://ppamdiag.claro.com/", "IMasociarWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PPAMDiag/IMasociarWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMASOCIARWS_WSDL_LOCATION = url;
        IMASOCIARWS_EXCEPTION = e;
    }

    public IMasociarWS_Service() {
        super(__getWsdlLocation(), IMASOCIARWS_QNAME);
    }

    public IMasociarWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMASOCIARWS_QNAME, features);
    }

    public IMasociarWS_Service(URL wsdlLocation) {
        super(wsdlLocation, IMASOCIARWS_QNAME);
    }

    public IMasociarWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMASOCIARWS_QNAME, features);
    }

    public IMasociarWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMasociarWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMasociarWS
     */
    @WebEndpoint(name = "IMasociarWSPort")
    public IMasociarWS getIMasociarWSPort() {
        return super.getPort(new QName("http://ppamdiag.claro.com/", "IMasociarWSPort"), IMasociarWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMasociarWS
     */
    @WebEndpoint(name = "IMasociarWSPort")
    public IMasociarWS getIMasociarWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ppamdiag.claro.com/", "IMasociarWSPort"), IMasociarWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMASOCIARWS_EXCEPTION!= null) {
            throw IMASOCIARWS_EXCEPTION;
        }
        return IMASOCIARWS_WSDL_LOCATION;
    }

}
