
package com.claro.ppamdiag;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMasociarWS", targetNamespace = "http://ppamdiag.claro.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMasociarWS {


    /**
     * 
     * @param estadoIM
     * @param tituloIM
     * @param grupoIM
     * @param fechaOpenIm
     * @param prioridadIM
     * @param incidencia
     * @param cpeip
     * @param usuario
     * @param idServicio
     * @return
     *     returns int
     */
    @WebMethod(operationName = "IMasociarWS")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "IMasociarWS", targetNamespace = "http://ppamdiag.claro.com/", className = "com.claro.ppamdiag.IMasociarWS_Type")
    @ResponseWrapper(localName = "IMasociarWSResponse", targetNamespace = "http://ppamdiag.claro.com/", className = "com.claro.ppamdiag.IMasociarWSResponse")
    @Action(input = "http://ppamdiag.claro.com/IMasociarWS/IMasociarWSRequest", output = "http://ppamdiag.claro.com/IMasociarWS/IMasociarWSResponse")
    public int iMasociarWS(
        @WebParam(name = "Incidencia", targetNamespace = "")
        String incidencia,
        @WebParam(name = "FechaOpenIm", targetNamespace = "")
        String fechaOpenIm,
        @WebParam(name = "EstadoIM", targetNamespace = "")
        String estadoIM,
        @WebParam(name = "GrupoIM", targetNamespace = "")
        String grupoIM,
        @WebParam(name = "TituloIM", targetNamespace = "")
        String tituloIM,
        @WebParam(name = "PrioridadIM", targetNamespace = "")
        String prioridadIM,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "IDServicio", targetNamespace = "")
        String idServicio,
        @WebParam(name = "CPEIP", targetNamespace = "")
        String cpeip);

}
