
package com.claro.matriz;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceNeighborsWs", targetNamespace = "http://matriz.claro.com/", wsdlLocation = "http://localhost:8080/GPONN/ServiceNeighborsWs?WSDL")
public class ServiceNeighborsWs_Service
    extends Service
{

    private final static URL SERVICENEIGHBORSWS_WSDL_LOCATION;
    private final static WebServiceException SERVICENEIGHBORSWS_EXCEPTION;
    private final static QName SERVICENEIGHBORSWS_QNAME = new QName("http://matriz.claro.com/", "ServiceNeighborsWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/GPONN/ServiceNeighborsWs?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICENEIGHBORSWS_WSDL_LOCATION = url;
        SERVICENEIGHBORSWS_EXCEPTION = e;
    }

    public ServiceNeighborsWs_Service() {
        super(__getWsdlLocation(), SERVICENEIGHBORSWS_QNAME);
    }

    public ServiceNeighborsWs_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICENEIGHBORSWS_QNAME, features);
    }

    public ServiceNeighborsWs_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICENEIGHBORSWS_QNAME);
    }

    public ServiceNeighborsWs_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICENEIGHBORSWS_QNAME, features);
    }

    public ServiceNeighborsWs_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceNeighborsWs_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceNeighborsWs
     */
    @WebEndpoint(name = "ServiceNeighborsWsPort")
    public ServiceNeighborsWs getServiceNeighborsWsPort() {
        return super.getPort(new QName("http://matriz.claro.com/", "ServiceNeighborsWsPort"), ServiceNeighborsWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceNeighborsWs
     */
    @WebEndpoint(name = "ServiceNeighborsWsPort")
    public ServiceNeighborsWs getServiceNeighborsWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://matriz.claro.com/", "ServiceNeighborsWsPort"), ServiceNeighborsWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICENEIGHBORSWS_EXCEPTION!= null) {
            throw SERVICENEIGHBORSWS_EXCEPTION;
        }
        return SERVICENEIGHBORSWS_WSDL_LOCATION;
    }

}
