
package com.claro.matriz;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceNeighborsWs", targetNamespace = "http://matriz.claro.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceNeighborsWs {


    /**
     * 
     * @param service
     * @param ip
     * @param mac
     * @return
     *     returns java.util.List<com.claro.matriz.ServiceOnt>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServiceRelation", targetNamespace = "http://matriz.claro.com/", className = "com.claro.matriz.GetServiceRelation")
    @ResponseWrapper(localName = "getServiceRelationResponse", targetNamespace = "http://matriz.claro.com/", className = "com.claro.matriz.GetServiceRelationResponse")
    @Action(input = "http://matriz.claro.com/ServiceNeighborsWs/getServiceRelationRequest", output = "http://matriz.claro.com/ServiceNeighborsWs/getServiceRelationResponse")
    public List<ServiceOnt> getServiceRelation(
        @WebParam(name = "service", targetNamespace = "")
        String service,
        @WebParam(name = "ip", targetNamespace = "")
        String ip,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param service
     * @param ipsw
     * @return
     *     returns java.util.List<com.claro.matriz.Ont>
     * @throws MalformedURLException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMatrizOntHuawei", targetNamespace = "http://matriz.claro.com/", className = "com.claro.matriz.GetMatrizOntHuawei")
    @ResponseWrapper(localName = "getMatrizOntHuaweiResponse", targetNamespace = "http://matriz.claro.com/", className = "com.claro.matriz.GetMatrizOntHuaweiResponse")
    @Action(input = "http://matriz.claro.com/ServiceNeighborsWs/getMatrizOntHuaweiRequest", output = "http://matriz.claro.com/ServiceNeighborsWs/getMatrizOntHuaweiResponse", fault = {
        @FaultAction(className = MalformedURLException_Exception.class, value = "http://matriz.claro.com/ServiceNeighborsWs/getMatrizOntHuawei/Fault/MalformedURLException"),
        @FaultAction(className = Exception_Exception.class, value = "http://matriz.claro.com/ServiceNeighborsWs/getMatrizOntHuawei/Fault/Exception")
    })
    public List<Ont> getMatrizOntHuawei(
        @WebParam(name = "service", targetNamespace = "")
        String service,
        @WebParam(name = "ipsw", targetNamespace = "")
        String ipsw)
        throws Exception_Exception, MalformedURLException_Exception
    ;

    /**
     * 
     * @param service
     * @param ipsw
     * @return
     *     returns java.util.List<com.claro.matriz.Ont>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMatrizOntZte", targetNamespace = "http://matriz.claro.com/", className = "com.claro.matriz.GetMatrizOntZte")
    @ResponseWrapper(localName = "getMatrizOntZteResponse", targetNamespace = "http://matriz.claro.com/", className = "com.claro.matriz.GetMatrizOntZteResponse")
    @Action(input = "http://matriz.claro.com/ServiceNeighborsWs/getMatrizOntZteRequest", output = "http://matriz.claro.com/ServiceNeighborsWs/getMatrizOntZteResponse")
    public List<Ont> getMatrizOntZte(
        @WebParam(name = "service", targetNamespace = "")
        String service,
        @WebParam(name = "ipsw", targetNamespace = "")
        String ipsw);

    /**
     * 
     * @param interfaceSW
     * @param swIp
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStateTroncalHuawei", targetNamespace = "http://matriz.claro.com/", className = "com.claro.matriz.GetStateTroncalHuawei")
    @ResponseWrapper(localName = "getStateTroncalHuaweiResponse", targetNamespace = "http://matriz.claro.com/", className = "com.claro.matriz.GetStateTroncalHuaweiResponse")
    @Action(input = "http://matriz.claro.com/ServiceNeighborsWs/getStateTroncalHuaweiRequest", output = "http://matriz.claro.com/ServiceNeighborsWs/getStateTroncalHuaweiResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://matriz.claro.com/ServiceNeighborsWs/getStateTroncalHuawei/Fault/Exception")
    })
    public String getStateTroncalHuawei(
        @WebParam(name = "interfaceSW", targetNamespace = "")
        String interfaceSW,
        @WebParam(name = "swIp", targetNamespace = "")
        String swIp)
        throws Exception_Exception
    ;

    /**
     * 
     * @param gponPort
     * @param swIp
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStateTroncalZte", targetNamespace = "http://matriz.claro.com/", className = "com.claro.matriz.GetStateTroncalZte")
    @ResponseWrapper(localName = "getStateTroncalZteResponse", targetNamespace = "http://matriz.claro.com/", className = "com.claro.matriz.GetStateTroncalZteResponse")
    @Action(input = "http://matriz.claro.com/ServiceNeighborsWs/getStateTroncalZteRequest", output = "http://matriz.claro.com/ServiceNeighborsWs/getStateTroncalZteResponse")
    public String getStateTroncalZte(
        @WebParam(name = "gponPort", targetNamespace = "")
        String gponPort,
        @WebParam(name = "swIp", targetNamespace = "")
        String swIp);

}
