
package co.com.claro.autodiagnosticoincidentesnegocios.soapClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RelationCpeOltPe", targetNamespace = "http://bussiness.model")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RelationCpeOltPe {


    /**
     * 
     * @param cpeIp
     * @param serviceId
     * @param cpeMac
     * @return
     *     returns java.util.List<client.cmdbwebservices.RelationCpeOltPeBean>
     */
    @WebMethod
    @WebResult(name = "getServiceRelationReturn", targetNamespace = "http://bussiness.model")
    @RequestWrapper(localName = "getServiceRelation", targetNamespace = "http://bussiness.model", className = "client.cmdbwebservices.GetServiceRelation")
    @ResponseWrapper(localName = "getServiceRelationResponse", targetNamespace = "http://bussiness.model", className = "client.cmdbwebservices.GetServiceRelationResponse")
    public List<RelationCpeOltPeBean> getServiceRelation(
        @WebParam(name = "serviceId", targetNamespace = "http://bussiness.model")
        String serviceId,
        @WebParam(name = "cpeIp", targetNamespace = "http://bussiness.model")
        String cpeIp,
        @WebParam(name = "cpeMac", targetNamespace = "http://bussiness.model")
        String cpeMac);

}
