
package co.com.claro.autodiagnosticoincidentesnegocios.soapClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "RelationCpeOltPeService", targetNamespace = "http://bussiness.model", wsdlLocation = "http://localhost:9090/CMDBWebServices/services/RelationCpeOltPe?wsdl")
@WebServiceClient(name = "RelationCpeOltPeService", targetNamespace = "http://bussiness.model")
public class RelationCpeOltPeService
    extends Service
{

    //private final static URL RELATIONCPEOLTPESERVICE_WSDL_LOCATION;
    private final static URL RELATIONCPEOLTPESERVICE_WSDL_LOCATION = null;
    //private final static WebServiceException RELATIONCPEOLTPESERVICE_EXCEPTION;
    private final static WebServiceException RELATIONCPEOLTPESERVICE_EXCEPTION = null;
    private final static QName RELATIONCPEOLTPESERVICE_QNAME = new QName("http://bussiness.model", "RelationCpeOltPeService");

    /*
    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/CMDBWebServices/services/RelationCpeOltPe?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RELATIONCPEOLTPESERVICE_WSDL_LOCATION = url;
        RELATIONCPEOLTPESERVICE_EXCEPTION = e;
    }
    */

    public RelationCpeOltPeService() {
        super(__getWsdlLocation(), RELATIONCPEOLTPESERVICE_QNAME);
    }

    public RelationCpeOltPeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RELATIONCPEOLTPESERVICE_QNAME, features);
    }

    public RelationCpeOltPeService(URL wsdlLocation) {
        super(wsdlLocation, RELATIONCPEOLTPESERVICE_QNAME);
    }

    public RelationCpeOltPeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RELATIONCPEOLTPESERVICE_QNAME, features);
    }

    public RelationCpeOltPeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RelationCpeOltPeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RelationCpeOltPe
     */
    @WebEndpoint(name = "RelationCpeOltPe")
    public RelationCpeOltPe getRelationCpeOltPe() {
        return super.getPort(new QName("http://bussiness.model", "RelationCpeOltPe"), RelationCpeOltPe.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RelationCpeOltPe
     */
    @WebEndpoint(name = "RelationCpeOltPe")
    public RelationCpeOltPe getRelationCpeOltPe(WebServiceFeature... features) {
        return super.getPort(new QName("http://bussiness.model", "RelationCpeOltPe"), RelationCpeOltPe.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RELATIONCPEOLTPESERVICE_EXCEPTION!= null) {
            throw RELATIONCPEOLTPESERVICE_EXCEPTION;
        }
        return RELATIONCPEOLTPESERVICE_WSDL_LOCATION;
    }

}
