
package client.runws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Runws", targetNamespace = "http://runws.webservices.pymes.diagnosticador.claro.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Runws {


    /**
     * 
     * @param cpeVendor
     * @param oltBrand
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "geList", targetNamespace = "http://runws.webservices.pymes.diagnosticador.claro.com.co/", className = "client.runws.GeList")
    @ResponseWrapper(localName = "geListResponse", targetNamespace = "http://runws.webservices.pymes.diagnosticador.claro.com.co/", className = "client.runws.GeListResponse")
    @Action(input = "http://runws.webservices.pymes.diagnosticador.claro.com.co/Runws/geListRequest", output = "http://runws.webservices.pymes.diagnosticador.claro.com.co/Runws/geListResponse")
    public List<String> geList(
        @WebParam(name = "oltBrand", targetNamespace = "")
        String oltBrand,
        @WebParam(name = "cpeVendor", targetNamespace = "")
        String cpeVendor);

    /**
     * 
     * @param cpeVendor
     * @param probeList
     * @param oltBrand
     * @return
     *     returns client.runws.DiagVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDiagnostic", targetNamespace = "http://runws.webservices.pymes.diagnosticador.claro.com.co/", className = "client.runws.GetDiagnostic")
    @ResponseWrapper(localName = "getDiagnosticResponse", targetNamespace = "http://runws.webservices.pymes.diagnosticador.claro.com.co/", className = "client.runws.GetDiagnosticResponse")
    @Action(input = "http://runws.webservices.pymes.diagnosticador.claro.com.co/Runws/getDiagnosticRequest", output = "http://runws.webservices.pymes.diagnosticador.claro.com.co/Runws/getDiagnosticResponse")
    public DiagVO getDiagnostic(
        @WebParam(name = "oltBrand", targetNamespace = "")
        String oltBrand,
        @WebParam(name = "cpeVendor", targetNamespace = "")
        String cpeVendor,
        @WebParam(name = "probeList", targetNamespace = "")
        List<ProbeVO> probeList);

    /**
     * 
     * @param serviceId
     * @return
     *     returns client.runws.DiagVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "diagnoseByService", targetNamespace = "http://runws.webservices.pymes.diagnosticador.claro.com.co/", className = "client.runws.DiagnoseByService")
    @ResponseWrapper(localName = "diagnoseByServiceResponse", targetNamespace = "http://runws.webservices.pymes.diagnosticador.claro.com.co/", className = "client.runws.DiagnoseByServiceResponse")
    @Action(input = "http://runws.webservices.pymes.diagnosticador.claro.com.co/Runws/diagnoseByServiceRequest", output = "http://runws.webservices.pymes.diagnosticador.claro.com.co/Runws/diagnoseByServiceResponse")
    public DiagVO diagnoseByService(
        @WebParam(name = "serviceId", targetNamespace = "")
        String serviceId);

    /**
     * 
     * @param serviceData
     * @return
     *     returns client.runws.DiagVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "diagnose", targetNamespace = "http://runws.webservices.pymes.diagnosticador.claro.com.co/", className = "client.runws.Diagnose")
    @ResponseWrapper(localName = "diagnoseResponse", targetNamespace = "http://runws.webservices.pymes.diagnosticador.claro.com.co/", className = "client.runws.DiagnoseResponse")
    @Action(input = "http://runws.webservices.pymes.diagnosticador.claro.com.co/Runws/diagnoseRequest", output = "http://runws.webservices.pymes.diagnosticador.claro.com.co/Runws/diagnoseResponse")
    public DiagVO diagnose(
        @WebParam(name = "serviceData", targetNamespace = "")
        ServiceData serviceData);

    /**
     * 
     * @param serviceData
     * @param testName
     * @return
     *     returns client.runws.ProbeVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "run", targetNamespace = "http://runws.webservices.pymes.diagnosticador.claro.com.co/", className = "client.runws.Run")
    @ResponseWrapper(localName = "runResponse", targetNamespace = "http://runws.webservices.pymes.diagnosticador.claro.com.co/", className = "client.runws.RunResponse")
    @Action(input = "http://runws.webservices.pymes.diagnosticador.claro.com.co/Runws/runRequest", output = "http://runws.webservices.pymes.diagnosticador.claro.com.co/Runws/runResponse")
    public ProbeVO run(
        @WebParam(name = "testName", targetNamespace = "")
        String testName,
        @WebParam(name = "serviceData", targetNamespace = "")
        ServiceData serviceData);

}
