
package client.runws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Runws", targetNamespace = "http://runws.webservices.pymes.diagnosticador.claro.com.co/", wsdlLocation = "http://localhost:8282/Diagpymews/Runws?wsdl")
public class Runws_Service
    extends Service
{

    private final static URL RUNWS_WSDL_LOCATION=null;
    private final static WebServiceException RUNWS_EXCEPTION=null;
    private final static QName RUNWS_QNAME = new QName("http://runws.webservices.pymes.diagnosticador.claro.com.co/", "Runws");

//    static {
//        URL url = null;
//        WebServiceException e = null;
//        try {
//            url = new URL("http://localhost:8282/Diagpymews/Runws?wsdl");
//        } catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        }
//        RUNWS_WSDL_LOCATION = url;
//        RUNWS_EXCEPTION = e;
//    }

    public Runws_Service() {
        super(__getWsdlLocation(), RUNWS_QNAME);
    }

    public Runws_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RUNWS_QNAME, features);
    }

    public Runws_Service(URL wsdlLocation) {
        super(wsdlLocation, RUNWS_QNAME);
    }

    public Runws_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RUNWS_QNAME, features);
    }

    public Runws_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Runws_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Runws
     */
    @WebEndpoint(name = "RunwsPort")
    public Runws getRunwsPort() {
        return super.getPort(new QName("http://runws.webservices.pymes.diagnosticador.claro.com.co/", "RunwsPort"), Runws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Runws
     */
    @WebEndpoint(name = "RunwsPort")
    public Runws getRunwsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://runws.webservices.pymes.diagnosticador.claro.com.co/", "RunwsPort"), Runws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RUNWS_EXCEPTION!= null) {
            throw RUNWS_EXCEPTION;
        }
        return RUNWS_WSDL_LOCATION;
    }

}
