
package com.claro.ppde;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SMPPDE", targetNamespace = "http://ppde.claro.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SMPPDE {


    /**
     * 
     * @return
     *     returns java.util.List<com.claro.ppde.PingPlotterDF>
     * @throws IOException_Exception
     */
    @WebMethod(operationName = "SMPPDE")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SMPPDE", targetNamespace = "http://ppde.claro.com/", className = "com.claro.ppde.SMPPDE_Type")
    @ResponseWrapper(localName = "SMPPDEResponse", targetNamespace = "http://ppde.claro.com/", className = "com.claro.ppde.SMPPDEResponse")
    @Action(input = "http://ppde.claro.com/SMPPDE/SMPPDERequest", output = "http://ppde.claro.com/SMPPDE/SMPPDEResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://ppde.claro.com/SMPPDE/SMPPDE/Fault/IOException")
    })
    public List<PingPlotterDF> smppde()
        throws IOException_Exception
    ;

}
