
package com.claro.ppde;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SMPPDE", targetNamespace = "http://ppde.claro.com/", wsdlLocation = "http://localhost:8080/PPDE/SMPPDE?WSDL")
public class SMPPDE_Service
    extends Service
{

    private final static URL SMPPDE_WSDL_LOCATION;
    private final static WebServiceException SMPPDE_EXCEPTION;
    private final static QName SMPPDE_QNAME = new QName("http://ppde.claro.com/", "SMPPDE");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PPDE/SMPPDE?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMPPDE_WSDL_LOCATION = url;
        SMPPDE_EXCEPTION = e;
    }

    public SMPPDE_Service() {
        super(__getWsdlLocation(), SMPPDE_QNAME);
    }

    public SMPPDE_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMPPDE_QNAME, features);
    }

    public SMPPDE_Service(URL wsdlLocation) {
        super(wsdlLocation, SMPPDE_QNAME);
    }

    public SMPPDE_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMPPDE_QNAME, features);
    }

    public SMPPDE_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SMPPDE_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SMPPDE
     */
    @WebEndpoint(name = "SMPPDEPort")
    public SMPPDE getSMPPDEPort() {
        return super.getPort(new QName("http://ppde.claro.com/", "SMPPDEPort"), SMPPDE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMPPDE
     */
    @WebEndpoint(name = "SMPPDEPort")
    public SMPPDE getSMPPDEPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ppde.claro.com/", "SMPPDEPort"), SMPPDE.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMPPDE_EXCEPTION!= null) {
            throw SMPPDE_EXCEPTION;
        }
        return SMPPDE_WSDL_LOCATION;
    }

}
